### ISSUE TITLE
verison of pytroch

### ISSUE THREAD

**Issue by zilinyan** [Randl/improved-improved-wgan-pytorch#1]
Hello @Randl ,
I have runtime error using your code. have you found the same issue?
What is the version of your pytorch.

Traceback (most recent call last):
  File "main.py", line 194, in <module>
    main()
  File "main.py", line 157, in main
    + args.lambda1 * loss_functions.gradient_penalty(fake_inputs.data, real_inputs.data, netD)
  File "/share/yan/improved-improved-wgan-pytorch/loss_functions.py", line 14, in gradient_penalty
    create_graph=True, retain_graph=True, only_inputs=True)[0]
  File "/home/yan/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 145, in grad
    inputs, allow_unused)
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

Greetings

**Comment by Randl** [comment]
which version of pytorch do you use?

**Comment by zilinyan** [comment]
> which version of pytorch do you use?

Thanks. now the problem is solved after downgrading my pytorch from 0.4.1 to 0.3.1.
